# Generated by Django 5.2.8 on 2025-11-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receipient',
            new_name='recipient',
        ),
    ]
