# Generated by Django 5.2.8 on 2025-11-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_created_1b3a4d_idx',
            old_name='jobs_created_7c32a5_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_categor_24d294_idx',
            old_name='jobs_categor_e41b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_locatio_8b2f8c_idx',
            old_name='jobs_locatio_8650dd_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_job_typ_f6c220_idx',
            old_name='jobs_job_typ_e7f4d4_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_company_73ae7f_idx',
            old_name='jobs_company_8219f2_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_search__684d46_gin',
            old_name='jobs_search__ee9a96_gin',
        ),
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
    ]
