# Generated by Django 5.2.8 on 2025-11-22 03:37

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (optional)', null=True, upload_to=users.models.user_avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), users.models.validate_image_size], verbose_name='Profile Picture'),
        ),
    ]
